### ISSUE TITLE
"Unhandled Python exception" While starting the program

### ISSUE THREAD

**Issue by TheDemystifier** [NikhilNarayana/FRC-YouTube-Uploader#55]
Nothing shows up, no UI, nothing. Just this line!

**Comment by NikhilNarayana** [comment]
What python version are you running? I know there are some issues with my dependencies and 3.7.4, so the latest usable version is 3.7.3

**Comment by TheDemystifier** [comment]
Yes, I'm running `Python '3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]'`

**Comment by NikhilNarayana** [comment]
Revert to 3.7.3 to use the program
